services:
  mysql:
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 7s
      timeout: 30s
      retries: 5
      start_period: 30s

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - two-tier

  flask:
    build: .

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops

    ports:
      - "5000:5000"

    depends_on:
      - mysql

    networks:
      - two-tier

    restart: always

networks:
  two-tier:

volumes:
  mysql-data: